// tools/lib/capfiles.mjs: capability DISCOVERY. Every src/presets/*.js (except the registry core) is a capability file;
// story.html and studio.html load the generated list src/presets/files.js instead of hard-coded <script> tags, so a new
// preset file is picked up without editing any page, the Director prompt or the compiler. A file may declare scripts it
// needs first (e.g. a vendored library) with header lines:   // @requires node_modules/d3-geo/dist/d3-geo.min.js
// render.mjs and the test harness call syncPresetFiles() before opening a page; it only writes when the list changed.
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../../', import.meta.url)), DIR = 'src/presets', OUT = `${ROOT}${DIR}/files.js`, CORE = new Set(['index.js', 'scene.js', 'gallery.js', 'files.js']);

export function presetFiles() {
  const files = readdirSync(ROOT + DIR).filter(f => f.endsWith('.js') && !CORE.has(f)).sort(), list = [];
  for (const f of files) {
    const head = readFileSync(`${ROOT}${DIR}/${f}`, 'utf8').split('\n').slice(0, 30);
    for (const l of head) { const m = l.match(/^\/\/\s*@requires\s+(\S+)/); if (m && !list.includes(m[1])) list.push(m[1]); }
    list.push(`${DIR}/${f}`);
  }
  return list;
}

export function syncPresetFiles() {
  const list = presetFiles();
  const src = `// GENERATED by tools/lib/capfiles.mjs (render.mjs and the tests refresh it): capability files in load order. Do not edit.\n` +
    `window.PRESET_FILES = ${JSON.stringify(list, null, 1).replace(/\n\s*/g, ' ')};\n`;
  if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== src) writeFileSync(OUT, src);
  return list;
}
