// collage_kit/scene.js: one short scene per family of the collage motion kit, joined by every reel transition. Data only.
// The cut-outs are collage_reel's (same files, same folder; generated by gen_assets for collage_reel), at sizes no larger
// than the reel's, so they are always sharp. A(tall, wide): a 9:16 value and a 16:9 value.
const A = (tall, wide) => ({ '9:16': tall, '16:9': wide });
const DIR = 'assets/stories/collage_reel/';
const SH = { dx: 8, dy: 12, blur: 12, opacity: .3, color: '#2A2A2E' };
const PAPER = { shadow: SH, border: 7, borderColor: '#FBFAF6', grain: .25 };
const SMALL = { shadow: { ...SH, dx: 5, dy: 8, blur: 8 }, border: 5, borderColor: '#FBFAF6', grain: .2 };
const BASE = { assets: DIR, background: '#F3F1EC', aspects: ['9:16', '16:9'], boil: { amp: 1.2, rot: .35 } };
const GROUND = (y = 1330) => ({ id: 'ground', file: 'ground_mint.png', size: [3200], at: A([540, y], [540, y - 40]), anchor: [.5, .2], paper: { shadow: { ...SH, dy: -5, opacity: .15 }, grain: .3 }, edgeOk: true });
const LBL = { font: 'display', weight: 700, size: A(64, 60), color: '#F7F3EA' };

// 1. weight and impact: drop + bounce, slam + shake, swing, pulse
SCENES.kit_impact = { ...BASE, duration: 2.8,
  camera: A([[0, 540, 1060, 1.12, 'ease'], [2.8, 540, 1040, 1.18, 'ease']], [[0, 540, 1000, 1, 'ease'], [2.8, 540, 990, 1.04, 'ease']]),
  layers: [
    GROUND(),
    { id: 'globe', file: 'globe.png', size: [420], at: A([330, 1150], [200, 1110]), anchor: [.5, .97], step: 2, subject: true, paper: PAPER,
      motion: [{ kind: 'drop', at: .1, height: 1100 }, { kind: 'shake', at: .98, amp: 8, rot: 2 }] },
    { id: 'fruit', file: 'tangerine.png', size: [300], at: A([760, 1190], [880, 1150]), anchor: [.5, .95], step: 2, subject: true, paper: PAPER,
      motion: [{ kind: 'slam', at: .8 }, { kind: 'pulse', at: 1.4, amp: .035, hz: 1.2 }] },
    { id: 'sign', file: 'road_sign.png', size: [220], at: A([560, 700], [1400, 640]), anchor: [.5, .03], step: 2, paper: SMALL, motion: [{ kind: 'swing', at: .5, amp: 30, enter: true }] },
  ],
  type: [{ text: 'น้ำหนัก แรงกระแทก', preset: 'cutout', at: 1.2, x: A(.5, .5), y: A(.12, .14), maxWidth: A(.86, .6), maxLines: 1, prefer: 'up',
    style: { font: 'display', weight: 800, size: A(78, 70), color: '#2E2E30' } }],
};

// 2. flight: a plane on a smooth banking path, another orbiting the globe; a smooth multi-key camera (tear in)
SCENES.kit_flight = { ...BASE, duration: 2.6, transition: { kind: 'tear', dur: .7 },
  camera: A([[0, 520, 980, 1.05, 'smooth'], [1.3, 560, 950, 1.12, 'smooth'], [2.6, 600, 960, 1.08, 'smooth']], [[0, 520, 960, 1, 'smooth'], [1.3, 560, 950, 1.05, 'smooth'], [2.6, 600, 960, 1.02, 'smooth']]),
  layers: [
    { id: 'globe2', file: 'globe.png', size: [460], at: [560, 1000], step: 2, subject: true, paper: PAPER, motion: [{ kind: 'sway', amp: 1.2, hz: .5 }] },
    { id: 'orbiter', file: 'airplane.png', size: [160], at: [0, 0], step: 2, paper: SMALL, motion: [{ kind: 'orbit', center: [560, 960], rx: 340, ry: 110, hz: .35, depth: .2 }] },
    { id: 'plane', file: 'airplane.png', size: [240], at: [0, 0], step: 2, paper: SMALL,
      motion: [{ kind: 'fly', at: 0, dur: 2.6, ease: 'linear', orient: true, bank: .6, path: A([[-200, 1500], [300, 1300], [700, 1450], [1300, 1250]], [[-600, 1350], [200, 1250], [900, 1400], [1700, 1200]]) }] },
  ],
  type: [{ text: 'เส้นทาง โค้ง ลื่นไหล', preset: 'label', at: .5, x: A(.5, .5), y: A(.13, .14), maxWidth: A(.86, .6), maxLines: 1, prefer: 'up', style: LBL }],
};

// 3. nature: falling petals, swaying trees, a replacement cycle (three frames on one spot) (iris in)
const PETALS = [[180, 0, .1], [420, .35, .5], [700, .2, .25], [900, .6, .75], [300, .9, .9], [820, 1.1, .4]];
SCENES.kit_nature = { ...BASE, duration: 2.6, transition: { kind: 'iris', dur: .7, focus: [.5, .55] },
  camera: A([[0, 540, 1000, 1.08, 'ease'], [2.6, 540, 1000, 1.12, 'ease']], [[0, 540, 980, 1, 'ease'], [2.6, 540, 980, 1.04, 'ease']]),
  layers: [
    GROUND(1340),
    ...[[250, 'tree_teal.png', 0], [830, 'tree_pink.png', .3]].map(([x, file, ph], i) => ({ id: 'tree' + i, file, size: [300], at: [x, 1350], anchor: [.5, .95], step: 2, paper: SMALL,
      motion: [{ kind: 'sway', amp: 2.5, hz: .5, phase: ph }] })),
    ...['person_a.png', 'person_b.png', 'person_c.png'].map((file, i) => ({ id: 'frame' + i, file, size: [null, 230], at: [540, 1450], anchor: [.5, 1], step: 2, paper: SMALL,
      motion: [{ kind: 'cycle', index: i, count: 3, fps: 6, pingpong: true }] })),
    ...PETALS.map(([x, at, ph], i) => ({ id: 'petal' + i, file: 'tree_pink.png', size: [70], at: [x, 520], step: 2, paper: SMALL,
      motion: [{ kind: 'flutter', at, dur: 2.2, fall: 900, phase: ph }] })),
  ],
  type: [{ text: 'ใบไม้ กลีบดอก ภาพสลับ', preset: 'cutout', at: .4, x: A(.5, .5), y: A(.12, .14), maxWidth: A(.86, .62), maxLines: 1, prefer: 'up',
    style: { font: 'display', weight: 800, size: A(70, 64), color: '#2E2E30' } }],
};

// 4. the road: a hand carries the truck in, it drives off along a curving road, facing its way (whip in)
SCENES.kit_road = { ...BASE, duration: 2.6, transition: { kind: 'whip', dur: .5, from: 'right' },
  camera: A([[0, 540, 1040, 1.08, 'ease'], [2.6, 540, 1020, 1.12, 'ease']], [[0, 540, 1000, 1, 'ease'], [2.6, 560, 990, 1.04, 'ease']]),
  layers: [
    { id: 'hill', file: 'hill.png', size: [2700], at: [540, 900], anchor: [.5, 0], paper: { shadow: { ...SH, dy: -6, opacity: .18 }, grain: .3 }, edgeOk: true },
    { id: 'road', file: 'road_ribbon.png', size: A([null, 1000], [null, 640]), at: A([560, 1900], [600, 1460]), anchor: [.5, 1], edgeOk: true, paper: { shadow: { ...SH, opacity: .2 } },
      motion: [{ kind: 'wipe', at: 0, dur: .8, path: [[.5, 1.05], [.42, .72], [.6, .38], [.5, -.05]], width: .95 }] },
    { id: 'truck', file: 'songthaew.png', size: [300], at: A([560, 1500], [620, 1300]), step: 2, subject: true, paper: PAPER,
      motion: [{ kind: 'place', at: .2, dur: .5, from: 'top', dist: 900 },
        { kind: 'fly', at: 1.1, dur: 1.5, ease: 'easeIn', scaleTo: .55, path: A([[560, 1500], [500, 1250], [640, 1050], [560, 900]], [[620, 1300], [560, 1150], [680, 1020], [600, 900]]) }] },
    { id: 'hand', file: 'hand_down.png', size: [null, 640], at: [0, 0], anchor: [.5, .93], step: 2, boil: false, edgeOk: true, paper: { shadow: SH, grain: .2 },
      motion: [{ kind: 'follow', target: 'truck', grip: [8, -60], until: .75, release: [0, -45] }, { kind: 'leave', at: .9, dur: .4, to: 'top' }] },
  ],
  type: [{ text: 'ส่งของ ขับไป', preset: 'label', at: .6, x: A(.5, .76), y: A(.12, .16), maxWidth: A(.8, .4), maxLines: 1, prefer: 'up', style: LBL }],
};

// 5. growth: a tree grows, fruit drop and bounce, a spin (fade in)
SCENES.kit_grow = { ...BASE, duration: 2.6, transition: { kind: 'fade', dur: .5 },
  camera: A([[0, 540, 1020, 1.08, 'ease'], [2.6, 540, 1000, 1.14, 'ease']], [[0, 540, 990, 1, 'ease'], [2.6, 540, 980, 1.05, 'ease']]),
  layers: [
    GROUND(1340),
    { id: 'bigtree', file: 'tangerine_tree.png', size: [620], at: [540, 1350], anchor: [.5, .97], step: 2, subject: true, paper: PAPER, motion: [{ kind: 'pop', at: .1, dur: .7, overshoot: 2.4 }, { kind: 'sway', amp: 1, hz: .4 }] },
    ...[[330, .9], [560, 1.1], [760, 1.3]].map(([x, at], i) => ({ id: 'fruit' + i, file: 'tangerine.png', size: [90], at: [x, 1430], anchor: [.5, .95], step: 2, paper: SMALL,
      motion: [{ kind: 'drop', at, height: 560, bounces: 3 }] })),
    { id: 'spinner', file: 'tangerine.png', size: [120], at: A([900, 700], [1300, 700]), step: 2, paper: SMALL, motion: [{ kind: 'pop', at: .4 }, { kind: 'spin', at: .6, dur: 1.6, turns: 1.5 }] },
  ],
  type: [{ text: 'เติบโต', preset: 'stamp', at: 1.2, x: A(.5, .5), y: A(.13, .15), maxWidth: A(.8, .5), maxLines: 1, prefer: 'up',
    style: { font: 'display', weight: 800, size: A(170, 140), color: '#3A3A3C' } }],
};

// 6. the end card (hard cut in)
SCENES.kit_end = { ...BASE, duration: 1.8, transition: { kind: 'cut' },
  camera: A([[0, 540, 960, 1, 'ease'], [1.8, 540, 960, 1.05, 'ease']], [[0, 540, 960, 1, 'ease'], [1.8, 540, 960, 1.04, 'ease']]),
  layers: [
    { id: 'tape', file: 'tape_mint.png', size: [900], at: [540, 1010], rot: -3, step: 2, paper: SMALL, motion: [{ kind: 'wipe', at: 0, dur: .4, dir: 'right' }] },
    { id: 'fruit_end', file: 'tangerine.png', size: [260], at: [540, 1240], step: 2, subject: true, paper: PAPER, motion: [{ kind: 'slam', at: .3 }] },
  ],
  type: [{ text: 'คอลลาจ โมชั่น คิท', preset: 'cutout', at: .5, x: .5, y: A(.42, .3), maxWidth: A(.86, .6), maxLines: 1, prefer: 'up',
    style: { font: 'display', weight: 800, size: A(86, 74), color: '#2E2E30' } }],
};

playCollage([SCENES.kit_impact, SCENES.kit_flight, SCENES.kit_nature, SCENES.kit_road, SCENES.kit_grow, SCENES.kit_end]);
