// GENERATED by tools/geo_raster.py. Do not edit.
(window.GEO = window.GEO || {}).relief = {"src": "src/geo/relief_mercator.jpg", "lat": 82.0, "size": [4096, 3468], "source": "Blue Marble colour (three-globe npm example image; appears to be NASA public-domain Blue Marble, not stated by the package) + hillshade from its heightmap"};
