// GENERATED by tools/lib/capfiles.mjs (render.mjs and the tests refresh it): capability files in load order. Do not edit.
window.PRESET_FILES = [ "src/presets/burst.js", "src/presets/camera.js", "src/presets/morph.js", "src/presets/pop.js", "src/presets/reveal.js", "src/presets/wipe.js" ];
