"""tools/footage.py: live-action FOOTAGE plates for mixed-media scenes (2D cartoon drawn over real video).

The engine draws a frame as a pure function of time, so a video plate is first turned into a frame sequence at the
story's fps (one JPEG per frame), and the camera motion in it is measured once, so cartoon layers can stick to it.

    python tools/footage.py prepare --in clip.mp4 --out assets/stories/<id>/footage/<name>/ [--start 2.3 --end 4.6]
                                    [--fps 24] [--width 1920] [--crop w:h:x:y]
    python tools/footage.py track   --dir assets/stories/<id>/footage/<name>/ [--point bus:0.5:0.62:0.55:0.06 ...]

prepare  frames f00001.jpg … at --fps (frame i shows time i / fps from --start), and meta.json (fps, size, frames,
         duration, source); footage.js carries meta and track for the page. --crop takes ffmpeg's w:h:x:y in source pixels.
track    track.json: `global`, the plate's camera motion per frame (cumulative translation in plate fractions, from
         phase correlation between consecutive frames: what makes stickers stay put on a hand-held or panning shot),
         (median over a 3 x 3 grid of tiles, so an object moving through part of the shot does not drag it),
         and per --point name:t:u:v:size a tracked point (u, v fractions of the plate at time t; size = template width,
         a fraction of the plate width), followed forwards and backwards from t by normalised cross-correlation, with
         a confidence per frame (low confidence = occluded or lost: check those frames).
numpy and Pillow only; ffmpeg for decoding.
"""
import argparse, json, os, subprocess, glob
import numpy as np
from PIL import Image


def prepare(a):
    os.makedirs(a.out, exist_ok=True)
    for f in glob.glob(os.path.join(a.out, 'f*.jpg')): os.remove(f)
    vf = ([f'crop={a.crop}'] if a.crop else []) + [f'fps={a.fps}', f'scale={a.width}:-2:flags=lanczos']
    cmd = ['ffmpeg', '-v', 'error', '-y'] + (['-ss', str(a.start)] if a.start else []) + ['-i', a.inp] + \
          (['-t', str(a.end - (a.start or 0))] if a.end else []) + ['-vf', ','.join(vf), '-q:v', '3', os.path.join(a.out, 'f%05d.jpg')]
    subprocess.run(cmd, check=True)
    files = sorted(glob.glob(os.path.join(a.out, 'f*.jpg')))
    if not files: raise SystemExit('no frames extracted')
    w, h = Image.open(files[0]).size
    meta = {'fps': a.fps, 'size': [w, h], 'frames': len(files), 'duration': len(files) / a.fps,
            'source': os.path.basename(a.inp), 'start': a.start or 0, 'crop': a.crop}
    json.dump(meta, open(os.path.join(a.out, 'meta.json'), 'w'), indent=1)
    write_js(a.out)
    print(f'{len(files)} frames {w}x{h} at {a.fps} fps -> {a.out}')


def write_js(d):
    """footage.js: meta + track as a script (a page opened from disk may load scripts and images, but not fetch JSON)"""
    rd = lambda f: json.load(open(os.path.join(d, f))) if os.path.exists(os.path.join(d, f)) else None
    open(os.path.join(d, 'footage.js'), 'w').write('// GENERATED by tools/footage.py\nwindow.FOOTAGE_DATA = ' + json.dumps({'meta': rd('meta.json'), 'track': rd('track.json')}) + ';\n')


def gray(f, width):
    im = Image.open(f).convert('L'); s = width / im.width
    return np.asarray(im.resize((width, round(im.height * s)), Image.BILINEAR), np.float32)


def phase_shift(a, b):
    """translation of b relative to a (px), by phase correlation with a Hann window; sub-pixel by parabola fit"""
    win = np.outer(np.hanning(a.shape[0]), np.hanning(a.shape[1]))
    A, B = np.fft.fft2((a - a.mean()) * win), np.fft.fft2((b - b.mean()) * win)
    R = A.conj() * B; R /= np.abs(R) + 1e-9
    r = np.fft.ifft2(R).real; y, x = np.unravel_index(np.argmax(r), r.shape)
    def sub(m, i, n):
        l, c, rr = m[(i - 1) % n], m[i], m[(i + 1) % n]; d = l - 2 * c + rr
        return i + (0.5 * (l - rr) / d if abs(d) > 1e-9 else 0)
    dy, dx = sub(r[:, x], y, r.shape[0]), sub(r[y, :], x, r.shape[1])
    if dy > r.shape[0] / 2: dy -= r.shape[0]
    if dx > r.shape[1] / 2: dx -= r.shape[1]
    return dx, dy


def camera_shift(a, b, grid=3):
    """the camera's move between two frames: the median of phase correlations over a grid of overlapping tiles, so a
    car or a person moving through part of the shot does not drag the whole plate with it"""
    H, W = a.shape; th, tw = H // 2, W // 2; shifts = []
    for gy in range(grid):
        for gx in range(grid):
            y0, x0 = int(gy * (H - th) / (grid - 1)), int(gx * (W - tw) / (grid - 1))
            ta, tb = a[y0:y0 + th, x0:x0 + tw], b[y0:y0 + th, x0:x0 + tw]
            if ta.std() > 2: shifts.append(phase_shift(ta, tb))
    if not shifts: return phase_shift(a, b)
    s = np.array(shifts); return float(np.median(s[:, 0])), float(np.median(s[:, 1]))


def ncc_track(frames, i0, u, v, size, W):
    """follow a template from frame i0 through the sequence (both directions); returns [[u, v, conf], ...] per frame"""
    n = len(frames); H = frames[0].shape[0]; tw = max(8, int(size * W)); r = max(6, tw)   # search radius = template width
    out = [None] * n
    def run(order):
        x, y = u * W, v * H
        T = None
        for i in order:
            f = frames[i]
            if T is None:
                y0, x0 = int(round(y - tw / 2)), int(round(x - tw / 2)); T = f[y0:y0 + tw, x0:x0 + tw].copy()
                out[i] = [x / W, y / H, 1.0]; continue
            ys, xs = int(round(y - tw / 2 - r)), int(round(x - tw / 2 - r))
            Sx0, Sy0 = max(0, xs), max(0, ys); S = f[Sy0:min(H, ys + tw + 2 * r), Sx0:min(W, xs + tw + 2 * r)]
            if S.shape[0] < tw or S.shape[1] < tw: out[i] = [x / W, y / H, 0.0]; continue
            win = np.lib.stride_tricks.sliding_window_view(S, (tw, tw))
            t0 = T - T.mean(); wm = win.mean(axis=(2, 3), keepdims=True); wz = win - wm
            num = (wz * t0).sum(axis=(2, 3)); den = np.sqrt((wz ** 2).sum(axis=(2, 3)) * (t0 ** 2).sum()) + 1e-6
            c = num / den; py, px = np.unravel_index(np.argmax(c), c.shape)
            x, y = Sx0 + px + tw / 2, Sy0 + py + tw / 2; conf = float(c[py, px])
            out[i] = [x / W, y / H, conf]
            if conf > .85:   # adapt slowly to appearance changes, only while confident
                y0, x0 = int(round(y - tw / 2)), int(round(x - tw / 2)); nT = f[y0:y0 + tw, x0:x0 + tw]
                if nT.shape == T.shape: T = .85 * T + .15 * nT
    run(range(i0, n)); run(range(i0, -1, -1))
    return [[round(p[0], 5), round(p[1], 5), round(p[2], 3)] for p in out]


def track(a):
    meta = json.load(open(os.path.join(a.dir, 'meta.json'))); files = sorted(glob.glob(os.path.join(a.dir, 'f*.jpg')))
    W = a.work; frames = [gray(f, W) for f in files]; H = frames[0].shape[0]
    g = [[0.0, 0.0]]
    for i in range(1, len(frames)):
        dx, dy = camera_shift(frames[i - 1], frames[i]); g.append([g[-1][0] + dx / W, g[-1][1] + dy / H])
    pts = {}
    for spec in a.point or []:
        name, t, u, v, size = spec.split(':'); i0 = min(len(frames) - 1, max(0, round(float(t) * meta['fps'])))
        pts[name] = ncc_track(frames, i0, float(u), float(v), float(size), W)
        low = sum(1 for p in pts[name] if p[2] < .6)
        print(f'point {name}: {len(frames)} frames, {low} low-confidence (< 0.6)')
    out = {'fps': meta['fps'], 'frames': len(frames), 'global': [[round(x, 5), round(y, 5)] for x, y in g], 'points': pts}
    json.dump(out, open(os.path.join(a.dir, 'track.json'), 'w')); write_js(a.dir)
    print(f'global motion: max drift {max(abs(x) for x, _ in g):.3f} x, {max(abs(y) for _, y in g):.3f} y (plate fractions) -> {a.dir}track.json')


if __name__ == '__main__':
    ap = argparse.ArgumentParser(); sub = ap.add_subparsers(dest='cmd', required=True)
    s = sub.add_parser('prepare'); s.add_argument('--in', dest='inp', required=True); s.add_argument('--out', required=True)
    s.add_argument('--start', type=float, default=0); s.add_argument('--end', type=float); s.add_argument('--fps', type=int, default=24)
    s.add_argument('--width', type=int, default=1920); s.add_argument('--crop')
    s = sub.add_parser('track'); s.add_argument('--dir', required=True); s.add_argument('--point', action='append'); s.add_argument('--work', type=int, default=480)
    a = ap.parse_args(); {'prepare': prepare, 'track': track}[a.cmd](a)
