// tools/geo_build.mjs: vendor base-map geometry for the map capabilities (src/presets/map.js) as plain scripts the page
// loads before drawing (file:// pages can't fetch JSON reliably). Source: Natural Earth via the world-atlas package
// (public-domain data, ISC package; devDependency). Coordinates rounded to 0.01° (~1 km): far below what a frame shows.
//   node tools/geo_build.mjs          → src/geo/land_50m.js (window.GEO.land50, a GeoJSON MultiPolygon)
import { readFileSync, writeFileSync } from 'node:fs';
import { feature } from 'topojson-client';

const round = a => typeof a[0] === 'number' ? [Math.round(a[0] * 100) / 100, Math.round(a[1] * 100) / 100] : a.map(round);
for (const [res, key] of [['50m', 'land50']]) {
  const topo = JSON.parse(readFileSync(`node_modules/world-atlas/land-${res}.json`, 'utf8'));
  const geo = feature(topo, topo.objects.land), g = geo.features ? geo.features[0].geometry : geo.geometry;
  g.coordinates = round(g.coordinates);
  const src = `// GENERATED by tools/geo_build.mjs from Natural Earth ${res} land (world-atlas ${JSON.parse(readFileSync('node_modules/world-atlas/package.json', 'utf8')).version}; public domain). Do not edit.\n` +
    `(window.GEO = window.GEO || {}).${key} = { source: 'Natural Earth 1:${res} land (naturalearthdata.com), public domain', geometry: ${JSON.stringify(g)} };\n`;
  writeFileSync(`src/geo/land_${res}.js`, src);
  console.log(`src/geo/land_${res}.js  ${(src.length / 1024).toFixed(0)} KB`);
}
