// tools/geo_build.mjs: vendor base-map geometry for the map capabilities (src/presets/map.js) as plain scripts the page
// loads before drawing (file:// pages can't fetch JSON reliably). Source: Natural Earth via the world-atlas package
// (public-domain data, ISC package; devDependency). Coordinates rounded to 0.01° (~1 km): far below what a frame shows.
//   node tools/geo_build.mjs          → src/geo/land_50m.js (window.GEO.land50, a GeoJSON MultiPolygon)
//                                       src/geo/countries_50m.js (window.GEO.countries50: { name → geometry }, modern borders)
import { readFileSync, writeFileSync } from 'node:fs';
import { feature } from 'topojson-client';

const round = a => typeof a[0] === 'number' ? [Math.round(a[0] * 100) / 100, Math.round(a[1] * 100) / 100] : a.map(round);
for (const [res, key] of [['50m', 'land50']]) {
  const topo = JSON.parse(readFileSync(`node_modules/world-atlas/land-${res}.json`, 'utf8'));
  const geo = feature(topo, topo.objects.land), g = geo.features ? geo.features[0].geometry : geo.geometry;
  g.coordinates = round(g.coordinates);
  const src = `// GENERATED by tools/geo_build.mjs from Natural Earth ${res} land (world-atlas ${JSON.parse(readFileSync('node_modules/world-atlas/package.json', 'utf8')).version}; public domain). Do not edit.\n` +
    `(window.GEO = window.GEO || {}).${key} = { source: 'Natural Earth 1:${res} land (naturalearthdata.com), public domain', geometry: ${JSON.stringify(g)} };\n`;
  writeFileSync(`src/geo/land_${res}.js`, src);
  console.log(`src/geo/land_${res}.js  ${(src.length / 1024).toFixed(0)} KB`);
}

// countries (modern Natural Earth admin-0 borders, by English name) for mapRegion
{
  const topo = JSON.parse(readFileSync('node_modules/world-atlas/countries-50m.json', 'utf8')), fc = feature(topo, topo.objects.countries), out = {};
  for (const f of fc.features) if (f.geometry) { f.geometry.coordinates = round(f.geometry.coordinates); out[f.properties.name] = f.geometry; }
  const src = `// GENERATED by tools/geo_build.mjs from Natural Earth 1:50m admin-0 countries (world-atlas; public domain). MODERN borders. Do not edit.\n` +
    `(window.GEO = window.GEO || {}).countries50 = ${JSON.stringify(out)};\n`;
  writeFileSync('src/geo/countries_50m.js', src);
  console.log(`src/geo/countries_50m.js  ${(src.length / 1024).toFixed(0)} KB, ${Object.keys(out).length} countries`);
}
