"""tools/geo_raster.py: build the satellite-style relief basemap for the map capabilities (mapBase style 'satellite').

Input: an equirectangular Earth colour image (+ optional heightmap and water mask). The default source is the Blue Marble
image shipped in the three-globe npm package (MIT package; the image appears to be NASA's public-domain Blue Marble, but
the package does not state it: for a production film use an official NASA Visible Earth Blue Marble download via --src).
Steps: hillshade from the heightmap (terrain reads like the reference style), a gentle land/sea grade (lusher land,
deeper teal sea), then ONE reprojection to Mercator (±82° lat), so the page draws it with a plain affine transform
under d3.geoMercator, exactly registered with the vector layers.

    python tools/geo_raster.py                        # fetches three-globe from the npm registry into .cache/
    python tools/geo_raster.py --src blue_marble.jpg [--height topo.png] [--water water.png] [--width 8192]
Output: src/geo/relief_mercator.jpg and src/geo/relief_mercator.js (bounds + source note; loaded by src/presets/map.js)
"""
import argparse, io, json, math, os, tarfile, urllib.request
import numpy as np
from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LAT = 82.0


def fetch_three_globe():
    cache = os.path.join(ROOT, '.cache', 'three-globe'); os.makedirs(cache, exist_ok=True)
    want = {'earth-blue-marble.jpg', 'earth-topology.png', 'earth-water.png'}
    if not all(os.path.exists(os.path.join(cache, f)) for f in want):
        meta = json.load(urllib.request.urlopen('https://registry.npmjs.org/three-globe/2.45.3'))
        tgz = urllib.request.urlopen(meta['dist']['tarball']).read()
        with tarfile.open(fileobj=io.BytesIO(tgz)) as t:
            for m in t.getmembers():
                if os.path.basename(m.name) in want:
                    open(os.path.join(cache, os.path.basename(m.name)), 'wb').write(t.extractfile(m).read())
    return [os.path.join(cache, f) for f in ('earth-blue-marble.jpg', 'earth-topology.png', 'earth-water.png')]


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--src'); ap.add_argument('--height'); ap.add_argument('--water')
    ap.add_argument('--width', type=int, default=4096); ap.add_argument('--quality', type=int, default=86)
    a = ap.parse_args()
    src, hgt, wat = (a.src, a.height, a.water) if a.src else fetch_three_globe()
    col = Image.open(src).convert('RGB'); W, H = col.size
    rgb = np.asarray(col, np.float32) / 255
    water = np.asarray(Image.open(wat).convert('L').resize((W, H), Image.BILINEAR), np.float32) / 255 if wat else None
    if hgt:   # hillshade (sun from the north-west, 45°) from the heightmap, applied to land only
        z = np.asarray(Image.open(hgt).convert('L').resize((W, H), Image.BICUBIC).filter(ImageFilter.GaussianBlur(1.2)), np.float32)
        gy, gx = np.gradient(z * (W / 2048) * 0.09)
        slope, aspect = np.arctan(np.hypot(gx, gy)), np.arctan2(-gx, gy)
        az, alt = math.radians(315), math.radians(45)
        shade = np.clip(np.sin(alt) * np.cos(slope) + np.cos(alt) * np.sin(slope) * np.cos(az - aspect), 0, 1)
        land = 1 - (water if water is not None else (z < 1).astype(np.float32))
        rgb *= (1 + (land * (shade - .62) * .85))[..., None]
    if water is not None:   # grade: lusher land, deeper teal sea (the documentary look), sea edges kept soft
        lw = water[..., None]; g = rgb.mean(axis=2, keepdims=True)
        land_c = g + (rgb - g) * 1.25; land_c[..., 1] *= 1.05
        sea_c = rgb * np.array([.35, .75, .72]) + np.array([.04, .2, .24])
        rgb = land_c * (1 - lw) + sea_c * lw
    rgb = np.clip(rgb, 0, 1)
    # equirectangular → Mercator (±LAT): every output row samples the input row of its latitude
    ymax = math.log(math.tan(math.pi / 4 + math.radians(LAT) / 2)); OW = a.width; OH = int(round(OW * 2 * ymax / (2 * math.pi)))
    ys = ymax - (np.arange(OH) + .5) / OH * 2 * ymax
    lat = np.degrees(np.arctan(np.sinh(ys))); rows = np.clip((90 - lat) / 180 * H - .5, 0, H - 1)
    r0 = np.floor(rows).astype(int); r1 = np.minimum(r0 + 1, H - 1); f = (rows - r0)[:, None, None]
    merc = rgb[r0] * (1 - f) + rgb[r1] * f
    out = Image.fromarray((merc * 255).astype(np.uint8)).resize((OW, OH), Image.LANCZOS)
    dst = os.path.join(ROOT, 'src', 'geo', 'relief_mercator.jpg'); out.save(dst, quality=a.quality, optimize=True)
    note = 'Blue Marble colour (three-globe npm example image; appears to be NASA public-domain Blue Marble, not stated by the package) + hillshade from its heightmap' if not a.src else f'{os.path.basename(src)} (+ hillshade)'
    open(os.path.join(ROOT, 'src', 'geo', 'relief_mercator.js'), 'w').write(
        '// GENERATED by tools/geo_raster.py. Do not edit.\n'
        f'(window.GEO = window.GEO || {{}}).relief = {json.dumps({"src": "src/geo/relief_mercator.jpg", "lat": LAT, "size": [OW, OH], "source": note})};\n')
    print(f'{dst}  {OW}x{OH}  {os.path.getsize(dst) / 1e6:.1f} MB')


if __name__ == '__main__':
    main()
